version: '2.1'
services:
  database:
    image: mysql:latest
    container_name: credit-card-db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-setup.sql:/docker-entrypoint-initdb.d/1.sql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    networks:
      backend:
        aliases:
          - "credit-card-db"
networks:
  backend:
    driver: bridge